[account_creator]
accounts_to_create = 1
threads = 1
log_level = "INFO"

[browser]
headless = false
enable_dev_tools = false
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"
element_wait_timeout = 30
cache_update_threshold = 0.3

[gproxy]
log_level = "INFO"

[email]
mail_provider = "xitroo"    # "imap", "guerrilla_mail", or "xitroo" are accepted values.
use_proxy_for_temp_mail = false

[email.guerrilla_mail]
domains = [
    "sharklasers.com",
    "guerrillamail.info",
    "grr.la",
    "guerrillamail.biz",
    "guerrillamail.com",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamail.com",
    "pokemail.net",
    "spam4.me",
]

[email.imap]
ip = "mail.domain.com"
port = 993
email = "catchall@domain.com"
password = "myCatchAllEmailPassword"
domains = []

[account]
username_length = 12
password = ""               # `password = ""` uses a randomly generated string.
random_password_length = 16
set_2fa = true

[proxies]
enabled = false
list = [
    # { ip = "my.ip.here", port = "port", username = "my_proxy_username", password = "my_proxy_password"},
    # { ip = "my.ip.here", port = "port"},
]